Repository Wanted-Team-G/assignment1-waynehills, pull requests merged in 2022-09, with the labels that each got.

#13 feat: 프로젝트 모델링, 시더파일 생성
  app.js
  components/posts/postModel.js
  components/users/userModel.js
  model/index.js
  package-lock.json
  package.json
  seeders/1-userSeeder.js
  seeders/2-postSeeder.js
Labels: WIP

#15 feat: config.js에 SECRET_KEY 추가
  config/config.js
Labels: 리뷰요청

#16 feat: errorHandler 미들웨어 생성
  app.js
  errors/httpErrors.js
  middlewares/errorHandler.js
Labels: 리뷰요청

#26 Feature/10
  components/posts/postService.js
Labels: 작업중, 리뷰요청

#28 Feature/27
  app.js
  components/users/userApi.js
  middlewares/userAuthChecker.js
  package.json
  swagger/json2yaml.js
  swagger/swagger-output.yaml
  swagger/swagger.js
Labels: 리뷰요청
